services:
  token-generator:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - COMMIT_HASH=$(git rev-parse --short HEAD)
    container_name: token-generator
    env_file:
      - .env
    ports:
      - '${PORT}:3000'
    restart: unless-stopped
